blank_issues_enabled: false
contact_links:
  - name: General Questions / Support
    url: https://github.com/matraux/filesystem/issues
    about: Please use issues only for bug reports or feature requests.