name: Quality Assurance

on:
  push:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    container:
      image: php:8.4-cli
    steps:
      - name: Install PHP extensions
        run: |
          apt-get update -y > /dev/null
          apt-get install -y zip libzip-dev > /dev/null
          docker-php-ext-install zip > /dev/null

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run Composer
        run: composer install --no-progress --prefer-dist

      - name: Prepare PHPStan config
        run: touch editor.phpstan.neon

      - name: Run PHPStan
        run: composer stan

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: php:8.4-cli
    steps:
      - name: Install PHP extensions
        run: |
          apt-get update -y > /dev/null
          apt-get install -y zip libzip-dev > /dev/null
          docker-php-ext-install zip > /dev/null

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run Composer
        run: composer install --no-progress --prefer-dist

      - name: Run Tests
        run: composer test