name: Quality Assurance

on:
  push:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Run Composer
        run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPStan
        run: composer stan

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Run Composer
        run: composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Run Tests
        run: composer test